<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="JAYESH" failures="3" tests="16" name="com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest" time="122.144" errors="0" timestamp="2023-07-15T17:39:55 EDT" skipped="3">
  <testcase classname="com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest" name="validateIfCorrectProductIsClicked" time="21.542"/>
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest" name="validateMonitorsPageIsLoaded" time="4.874"/>
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest" name="validateSlider" time="5.728">
    <skipped/>
  </testcase> <!-- validateSlider -->
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest" name="validateLogin" time="5.795"/>
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest" name="validateRegistrationSuccess" time="6.855"/>
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest" name="validateLoginUsingInValidCredentials" time="5.692">
    <skipped/>
  </testcase> <!-- validateLoginUsingInValidCredentials -->
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest" name="validateLogin" time="5.634"/>
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest" name="validateLoginUsingValidCredentials" time="6.001"/>
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest" name="validateIPhoneAddedToCartSuccessfully" time="6.463"/>
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest" name="validateMacBookAddedToWishListSuccessfully" time="9.901">
    <skipped/>
  </testcase> <!-- validateMacBookAddedToWishListSuccessfully -->
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest" name="validateMacBookAddedToWishListSuccessfully" time="9.856">
    <failure message="Wrong Count expected [1] but found [4]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Wrong Count expected [1] but found [4]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest.validateMacBookAddedToWishListSuccessfully(YourStoreTest.java:119)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateMacBookAddedToWishListSuccessfully -->
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest" name="validateSlider" time="6.391">
    <failure message="Slider values doesnot match with Expected values" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Slider values doesnot match with Expected values
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.assertEquals(Assert.java:1359)
at com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest.validateSlider(YourStoreTest.java:182)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateSlider -->
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest" name="validateWishListCount" time="7.580"/>
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest" name="validateLoginUsingInValidCredentials" time="6.004">
    <failure message="invalid expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: invalid expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest.validateLoginUsingInValidCredentials(YourStoreTest.java:83)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateLoginUsingInValidCredentials -->
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest" name="validateUnitPrice" time="6.878"/>
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest" name="validateNavigationInRegistrationPage" time="6.950"/>
  <system-out/>
</testsuite> <!-- com.naveenautomationlabs.AutomationFramework.Tests.YourStoreTest -->
